# Generated by Django 2.2.5 on 2019-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
